### ISSUE TITLE
Ensure multiple route parameters in the same path works

### ISSUE THREAD

**Issue by arthurfiorette** [kitajs/kitajs#369]
Routes like `/users/[userid]-[userage]` should work, not only `/users/[userid]/[userage]`.

**Comment by arthurfiorette** [comment]
They probably already work, but there's no tests for now...

**Comment by joao-cabral** [comment]
Hello, I'm interested in working on this issue.

**Comment by arthurfiorette** [comment]
Awesome! I'm almost sure this already works, so just creating a test similar to this one should be enough.

https://github.com/kitajs/kitajs/tree/main/packages/parser/test/paths
